### ISSUE TITLE
TypeError on property 'Name' of undefined

### ISSUE THREAD

**Issue by CarolineBoyer** [Kamahl19/hapi-webpack-plugin-2#2]
Thank you for the plugin and hard work.

When trying to follow exactly your exemple 'With config object' (will also happen when using the 'With configPath'), I went on and putted the `server.register` into a try/catch and the following error is triggered whatever I try :
TypeError: Cannot read property 'name' of undefined

This doesn't happen with other plugins or so. Do you know what I couold have done wrong ?
The trace doesn't give me much help at all :

Trace: Error when Linking Webpack ======= TypeError: Cannot read property 'name' of undefined
    at start (C:\Users\name\IDEFolder\projectName\server\server.js:57:11)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Line 57 correspond to the catch error console.trace(error).

Here is an idea of the code 

```javascript
try {
		server.register({
  plugin: require('hapi-webpack-plugin-2'),
  options: {
    config: {
      compiler: webpack({
        // webpack options http://webpack.github.io
      }),
      assets: {
        // webpack-dev-middleware options https://github.com/webpack/webpack-dev-middleware
      },
      hot: {
        // webpack-hot-middleware options https://github.com/glenjamin/webpack-hot-middleware
      },
    },
  },
});

	} catch (errorWhenLinkingWebpack) {
		console.trace("Error when Linking Webpack ======= " + errorWhenLinkingWebpack)
	}
```

Any idea ? It feels to me like hapi.register can't have access to the plugin created and its name... I might be wrong though.

**Comment by 0-M** [comment]
@CarolineBoyer did you get this working? I'm running into the same issue w/ webpack 4 & Hapi v17

**Comment by mmatusevich** [comment]
> @CarolineBoyer did you get this working? I'm running into the same issue w/ webpack 4 & Hapi v17

you can do this 
``` 
server.register({
                plugin: require('hapi-webpack-plugin-2').default,
                options: {...}
``` 
that worked for me
